name: winterchord-sandbox
favicon: null
layout_spectrum: 0.1716469954699278
typography_spectrum: 0.6260623780544847
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5055638398043811
  lightness: 0.7603028502780944
  saturation: 0.301476676017046
  rhythmicContrast: 0.33631789055652916
purpose: []
